import type { APIRoute } from 'astro';

// Redirect /sitemap.xml to the canonical sitemap generated by @astrojs/sitemap.
// This avoids duplicate/conflicting sitemaps for crawlers.
export const GET: APIRoute = ({ site, url }) => {
  const origin = site?.origin ?? url.origin;
  const target = new URL('/sitemap-index.xml', origin).href;

  return new Response(null, {
    status: 308,
    headers: {
      Location: target
    }
  });
};
