import type { APIRoute } from 'astro';

export const GET: APIRoute = ({ site, request }) => {
  // Redirect to the sitemap generated by @astrojs/sitemap to avoid duplicate sitemaps.
  // Derive origin from the configured site URL or fall back to the incoming request origin.
  const requestUrl = new URL(request.url);
  const origin = site?.origin ?? requestUrl.origin;
  const target = new URL('/sitemap-index.xml', origin).href;

  return new Response(null, {
    status: 308,
    headers: {
      Location: target
    }
  });
};
