import type { APIRoute } from 'astro';

export const GET: APIRoute = () => {
  // Redirect to the sitemap generated by @astrojs/sitemap to avoid duplicate sitemaps.
  // Use a relative URL so the redirect always stays on the current origin,
  // regardless of the configured `site` value or deployment domain.
  return new Response(null, {
    status: 308,
    headers: {
      Location: '/sitemap-index.xml'
    }
  });
};
